const {chromium}=require('../recorder/node_modules/playwright-core');
const http=require('http'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../..');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.png':'image/png'};
const server=http.createServer((q,r)=>{const p=path.join(root,decodeURIComponent(new URL(q.url,'http://local').pathname));if(!p.startsWith(root+path.sep)){r.writeHead(403).end();return}fs.readFile(p,(e,data)=>{if(e){r.writeHead(404).end();return}r.writeHead(200,{'Content-Type':mime[path.extname(p)]||'application/octet-stream','Cache-Control':'no-store'});r.end(data)})});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{await new Promise(r=>server.listen(8092,r));const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true});const ctx=await browser.newContext({viewport:{width:1920,height:1080},recordVideo:{dir:path.join(__dirname,'raw'),size:{width:1920,height:1080}}});
await ctx.addInitScript(()=>{if(location.pathname.includes('editor.html')){localStorage.clear();localStorage.setItem('mathpaster_settings',JSON.stringify({layoutVersion:3,popupWidth:1180,popupHeight:640,themePreset:'precision',symbolGridWidth:66,symbolHeight:56,symbolFontSize:28,tabPaddingH:20,tabPaddingV:9,tabFontSize:16,actionBtnPaddingX:32,actionBtnPaddingY:12,actionBtnFontSize:20,showLatexBar:true}));}});
const page=await ctx.newPage();const created=Date.now();await page.goto('http://localhost:8092/promo%20video/motion-showcase/ai-stage.html');const frame=page.frameLocator('iframe');await frame.locator('#mf').waitFor({state:'visible'});const real=page.frames().find(f=>f.url().includes('/mathlive/editor.html'));await real.addStyleTag({content:'html{background:#101717!important}body{align-items:center!important;padding:0!important}#mf{font-size:40px!important}'});await sleep(700);
let start=Date.now();const offset=(start-created)/1000;const events=[];const log=kind=>events.push({t:(Date.now()-start)/1000,kind});
const until=async s=>{const left=s*1000-(Date.now()-start);if(left>0)await sleep(left);else if(left < -1200)console.log('Schedule behind',s,Math.round(-left));};
const scene=async(a,b,c,d)=>{log('scene');await page.evaluate(v=>window.scene(...v),[a,b,c,d]);};
const click=async loc=>{const b=await loc.boundingBox();if(!b)throw Error('Missing target');const x=b.x+b.width/2,y=b.y+b.height/2;await page.evaluate(([x,y])=>window.move(x,y),[x,y]);await page.mouse.move(x,y);await sleep(450);await page.evaluate(()=>window.tap());await page.mouse.click(x,y);log('click');await sleep(150)};
const type=async s=>{for(const c of s){await page.keyboard.type(c);log('key');await sleep(130)}};
const key=async k=>{await page.keyboard.press(k);log('key');await sleep(130)};
const clear=async()=>{await click(frame.locator('#mf'));await key('Control+a');await key('Backspace')};
const check=async label=>console.log(label,await frame.locator('#mf').evaluate(e=>e.value));
await page.evaluate(()=>{window.move(1480,700);window.scene('From equation to understanding.','MathPaster writes the notation. Your AI handles the next step.','Illustrative AI conversation. Real MathPaster insertion.','04 — SEND & SOLVE')});
await click(page.locator('#result'));await type('Evaluate this integral: ');
await page.evaluate(()=>window.show());await sleep(650);await click(frame.locator('#mf'));await type('int');await sleep(450);await type('1');await key('ArrowRight');await type('0');await key('End');await type('x^2');await key('ArrowRight');await type('dx');await check('integral');await sleep(400);await click(frame.locator('#insert-btn'));await sleep(450);await click(page.locator('#send'));await sleep(3600);await page.screenshot({path:path.join(__dirname,'last-editor.png')});
const video=page.video();await ctx.close();await video.saveAs(path.join(__dirname,'fresh-take.webm'));fs.writeFileSync(path.join(__dirname,'take.json'),JSON.stringify({offset,events},null,2));await browser.close();server.close();console.log('Fresh take complete',offset);})().catch(e=>{console.error(e);process.exit(1)});
