export const PALETTE_DATA = {
  "Common": [
    { label: "α",   latex: "\\alpha" },
    { label: "β",   latex: "\\beta" },
    { label: "γ",   latex: "\\gamma" },
    { label: "θ",   latex: "\\theta" },
    { label: "π",   latex: "\\pi" },
    { label: "σ",   latex: "\\sigma" },
    { label: "Σ",   latex: "\\sum" },
    { label: "√",   latex: "\\sqrt{#0}" },
    { label: "x²",  latex: "#0^{2}" },
    { label: "<div style='display:flex;flex-direction:column;font-size:11.5px;line-height:1;align-items:center;'><span style='border-bottom:1px solid currentColor;padding:0 3px 1px 3px;'>⬚</span><span style='padding-top:2px;'>⬚</span></div>", latex: "\\frac{#0}{#1}" },
    { label: "±",   latex: "\\pm" },
    { label: "≠",   latex: "\\neq" },
    { label: "≤",   latex: "\\leq" },
    { label: "≥",   latex: "\\geq" },
    { label: "→",   latex: "\\to" },
    { label: "∞",   latex: "\\infty" },
    {"label": "≈", "latex": "\\approx"},
    {"label": "×", "latex": "\\times"},
    {"label": "⋅", "latex": "\\cdot"},
    {"latex": "\\sqrt[#0]{#1}"},
    {"latex": "#0^{#1}"},
    {"latex": "#0_{#1}"},
    {"latex": "\\left|#0\\right|"},
    {"label": "ln", "latex": "\\ln"},
    {"label": "log", "latex": "\\log"},
  ],
  "Calculus": [
    { label: "∫",   latex: "\\int" },
    { label: "<div style='display:flex;align-items:center;'><span style='font-size:25px;'>∫</span><div style='display:flex;flex-direction:column;font-size:11.5px;line-height:1;margin-left:2px;'><span>b</span><span style='margin-top:7px;'>a</span></div></div>", latex: "\\int_{#0}^{#1}" },
    { label: "∬",  latex: "\\iint" },
    { label: "∬<sub style='font-size:11.5px;margin-left:-2px;margin-top:9px;'>D</sub>", latex: "\\iint_{#0}^{#1}" },
    { label: "∭",  latex: "\\iiint" },
    { label: "∭<sub style='font-size:11.5px;margin-left:-2px;margin-top:9px;'>V</sub>", latex: "\\iiint_{#0}^{#1}" },
    { label: "∮",  latex: "\\oint" },
    { label: "∮<sub style='font-size:11.5px;margin-left:-2px;margin-top:9px;'>C</sub>", latex: "\\oint_{#0}^{#1}" },
    { label: "lim",  latex: "\\lim_{#0}" },
    { label: "∂",   latex: "\\partial" },
    { label: "∇",   latex: "\\nabla" },
    { label: "<div style='display:flex;flex-direction:column;font-size:12.5px;line-height:1.1;align-items:center;'><span style='border-bottom:1px solid currentColor;padding:0 2px;'>d</span><span>dx</span></div>", latex: "\\frac{d}{dx}" },
    { label: "∑",   latex: "\\sum" },
    { label: "<div style='display:flex;align-items:center;'><span style='font-size:21px;'>∑</span><div style='display:flex;flex-direction:column;font-size:10.5px;line-height:1.1;margin-left:2px;'><span>n</span><span style='margin-top:5px;'>i</span></div></div>", latex: "\\sum_{#0}^{#1}" },
    { label: "∏",   latex: "\\prod" },
    { label: "<div style='display:flex;align-items:center;'><span style='font-size:21px;'>∏</span><div style='display:flex;flex-direction:column;font-size:10.5px;line-height:1.1;margin-left:2px;'><span>n</span><span style='margin-top:5px;'>i</span></div></div>", latex: "\\prod_{#0}^{#1}" },
    { label: "′", latex: "'" },
    {"latex": "\\frac{\\partial}{\\partial x}"},
    {"latex": "\\frac{d^2}{dx^2}"},
    {"latex": "\\frac{\\partial^2}{\\partial x^2}"},
    {"label": "sin", "latex": "\\sin"},
    {"label": "cos", "latex": "\\cos"},
    {"label": "tan", "latex": "\\tan"},
    {"latex": "e^{#0}"},
    {"label": "<span style='font-size:14px;'>lim sup</span>", "latex": "\\limsup_{#0}"},
    {"label": "<span style='font-size:14px;'>lim inf</span>", "latex": "\\liminf_{#0}"},
    {"label": "∇²", "latex": "\\nabla^2"},
    {"label": "sinh", "latex": "\\sinh"},
    {"label": "cosh", "latex": "\\cosh"},
    {"label": "tanh", "latex": "\\tanh"},
  ],
  "Linear Algebra": [
    { label: "[ ]",  matrixType: "bmatrix" },
    { label: "( )",  matrixType: "pmatrix" },
    { label: "| |",  matrixType: "vmatrix" },
    { label: "det",  latex: "\\det" },
    { label: "Tr",   latex: "\\operatorname{Tr}" },
    { label: "dim",  latex: "\\dim" },
    { label: "ker",  latex: "\\ker" },
    { label: "⊗",   latex: "\\otimes" },
    { label: "⊕",   latex: "\\oplus" },
    { label: "⋅",   latex: "\\cdot" },
    { label: "×",   latex: "\\times" },
    {"latex": "\\vec{#0}"},
    {"latex": "\\left\\lVert#0\\right\\rVert"},
    {"latex": "\\left\\langle#0,#1\\right\\rangle"},
    {"label": "Aᵀ", "latex": "#0^{\\mathsf{T}}"},
    {"label": "A⁻¹", "latex": "#0^{-1}"},
    {"label": "A†", "latex": "#0^{\\dagger}"},
    {"label": "rank", "latex": "\\operatorname{rank}"},
    {"label": "span", "latex": "\\operatorname{span}"},
    {"label": "Im", "latex": "\\operatorname{Im}"},
    {"label": "⊥", "latex": "\\perp"},
    {"label": "⋮", "latex": "\\vdots"},
    {"label": "⋱", "latex": "\\ddots"},
  ],
  "Statistics": [
    { label: "μ", latex: "\\mu" },
    { label: "σ", latex: "\\sigma" },
    { label: "σ²", latex: "\\sigma^2" },
    { label: "ρ", latex: "\\rho" },
    { label: "E[X]", latex: "\\mathbb{E}[X]" },
    { label: "Var", latex: "\\operatorname{Var}" },
    { label: "Cov", latex: "\\operatorname{Cov}" },
    { label: "P(A)", latex: "\\mathbb{P}(A)" },
    { label: "∼", latex: "\\sim" },
    { label: "≈", latex: "\\approx" },
    { label: "∝", latex: "\\propto" },
    { latex: "\\binom{#0}{#1}" },
    {"latex": "\\bar{#0}"},
    {"latex": "\\hat{#0}"},
    {"label": "<span style='font-size:14px;'>P(A|B)</span>", "latex": "\\mathbb{P}\\left(#0\\mid#1\\right)"},
    {"label": "<span style='font-size:14px;'>E[X|Y]</span>", "latex": "\\mathbb{E}\\left[#0\\mid#1\\right]"},
    {"label": "Corr", "latex": "\\operatorname{Corr}"},
    {"label": "N", "latex": "\\mathcal{N}\\left(#0,#1\\right)"},
    {"label": "Bern", "latex": "\\operatorname{Bern}\\left(#0\\right)"},
    {"label": "Bin", "latex": "\\operatorname{Bin}\\left(#0,#1\\right)"},
    {"label": "Pois", "latex": "\\operatorname{Pois}\\left(#0\\right)"},
    {"label": "n!", "latex": "#0!"},
  ],
  "Groups": [
    { label: "ℝ", latex: "\\mathbb{R}" },
    { label: "ℂ", latex: "\\mathbb{C}" },
    { label: "ℤ", latex: "\\mathbb{Z}" },
    { label: "ℕ", latex: "\\mathbb{N}" },
    { label: "ℚ", latex: "\\mathbb{Q}" },
    { label: "∈", latex: "\\in" },
    { label: "∉", latex: "\\notin" },
    { label: "⊂", latex: "\\subset" },
    { label: "⊆", latex: "\\subseteq" },
    { label: "∪", latex: "\\cup" },
    { label: "∩", latex: "\\cap" },
    { label: "∅", latex: "\\emptyset" },
    { label: "∖", latex: "\\setminus" },
    {"label": "⊃", "latex": "\\supset"},
    {"label": "⊇", "latex": "\\supseteq"},
    {"label": "⊊", "latex": "\\subsetneq"},
    {"label": "⊈", "latex": "\\nsubseteq"},
    {"label": "∋", "latex": "\\ni"},
    {"label": "⋃", "latex": "\\bigcup_{#0}^{#1}"},
    {"label": "⋂", "latex": "\\bigcap_{#0}^{#1}"},
    {"label": "Aᶜ", "latex": "#0^{c}"},
    {"label": "𝒫(A)", "latex": "\\mathcal{P}\\left(#0\\right)"},
    {"label": "𝔽", "latex": "\\mathbb{F}"},
  ],
  "Logic": [
    { label: "∀", latex: "\\forall" },
    { label: "∃", latex: "\\exists" },
    { label: "∄", latex: "\\nexists" },
    { label: "⇒", latex: "\\implies" },
    { label: "⇔", latex: "\\iff" },
    { label: "∧", latex: "\\land" },
    { label: "∨", latex: "\\lor" },
    { label: "¬", latex: "\\neg" },
    { label: "∴", latex: "\\therefore" },
    { label: "∵", latex: "\\because" },
    { label: "≡", latex: "\\equiv" },
    { label: "⊤", latex: "\\top" },
    { label: "⊥", latex: "\\bot" },
    {"label": "←", "latex": "\\leftarrow"},
    {"label": "↔", "latex": "\\leftrightarrow"},
    {"label": "↦", "latex": "\\mapsto"},
    {"label": "⊨", "latex": "\\models"},
    {"label": "⊢", "latex": "\\vdash"},
    {"label": "⊬", "latex": "\\nvdash"},
    {"label": "∃!", "latex": "\\exists!"},
  ],
  "Greek": [
    { label: "α", latex: "\\alpha" },
    { label: "β", latex: "\\beta" },
    { label: "γ", latex: "\\gamma" },
    { label: "δ", latex: "\\delta" },
    { label: "ϵ", latex: "\\epsilon" },
    { label: "ε", latex: "\\varepsilon" },
    { label: "ζ", latex: "\\zeta" },
    { label: "η", latex: "\\eta" },
    { label: "θ", latex: "\\theta" },
    { label: "ϑ", latex: "\\vartheta" },
    { label: "ι", latex: "\\iota" },
    { label: "κ", latex: "\\kappa" },
    { label: "ϰ", latex: "\\varkappa" },
    { label: "λ", latex: "\\lambda" },
    { label: "μ", latex: "\\mu" },
    { label: "ν", latex: "\\nu" },
    { label: "ξ", latex: "\\xi" },
    { label: "ο", latex: "o" },
    { label: "π", latex: "\\pi" },
    { label: "ϖ", latex: "\\varpi" },
    { label: "ρ", latex: "\\rho" },
    { label: "ϱ", latex: "\\varrho" },
    { label: "σ", latex: "\\sigma" },
    { label: "ς", latex: "\\varsigma" },
    { label: "τ", latex: "\\tau" },
    { label: "υ", latex: "\\upsilon" },
    { label: "ϕ", latex: "\\phi" },
    { label: "φ", latex: "\\varphi" },
    { label: "χ", latex: "\\chi" },
    { label: "ψ", latex: "\\psi" },
    { label: "ω", latex: "\\omega" },
    // Standard LaTeX uses Latin glyphs for the identical-looking Greek capitals.
    {"label": "Α", "latex": "A"},
    {"label": "Β", "latex": "B"},
    {"label": "Γ", "latex": "\\Gamma"},
    {"label": "Δ", "latex": "\\Delta"},
    {"label": "Ε", "latex": "E"},
    {"label": "Ζ", "latex": "Z"},
    {"label": "Η", "latex": "H"},
    {"label": "Θ", "latex": "\\Theta"},
    {"label": "Ι", "latex": "I"},
    {"label": "Κ", "latex": "K"},
    {"label": "Λ", "latex": "\\Lambda"},
    {"label": "Μ", "latex": "M"},
    {"label": "Ν", "latex": "N"},
    {"label": "Ξ", "latex": "\\Xi"},
    {"label": "Ο", "latex": "O"},
    {"label": "Π", "latex": "\\Pi"},
    {"label": "Ρ", "latex": "P"},
    {"label": "Σ", "latex": "\\Sigma"},
    {"label": "Τ", "latex": "T"},
    {"label": "Υ", "latex": "\\Upsilon"},
    {"label": "Φ", "latex": "\\Phi"},
    {"label": "Χ", "latex": "X"},
    {"label": "Ψ", "latex": "\\Psi"},
    {"label": "Ω", "latex": "\\Omega"},
  ]
};
