import React from 'react';
import {AbsoluteFill, Sequence, Audio, Img, staticFile, useCurrentFrame, interpolate, Easing} from 'remotion';
import katex from 'katex';
import 'katex/dist/katex.min.css';

const mint='#a5e6cd', ink='#ecf5f1', muted='#8ea39a';
const ease=Easing.bezier(.16,1,.3,1);
const ramp=(f:number,a:number,b:number,x=0,y=1)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease});
const M:React.FC<{tex:string,size?:number}>=({tex,size=66})=><span style={{fontSize:size}} dangerouslySetInnerHTML={{__html:katex.renderToString(tex,{throwOnError:false})}}/>;
const Key:React.FC<React.PropsWithChildren>=({children})=><span style={{display:'inline-block',padding:'10px 20px',border:'1px solid #ffffff28',borderBottom:'4px solid #ffffff25',borderRadius:12,background:'#ffffff09',fontSize:28,color:ink,fontFamily:'monospace'}}>{children}</span>;
const Caption:React.FC<{label:string,title:string,sub?:string}>=({label,title,sub})=><div><div style={{fontSize:19,letterSpacing:5,color:mint,marginBottom:24}}>{label}</div><h1 style={{fontSize:76,lineHeight:1.06,letterSpacing:-3,fontWeight:650,margin:0,whiteSpace:'pre-line'}}>{title}</h1>{sub&&<p style={{fontSize:27,color:muted,lineHeight:1.5,marginTop:26,maxWidth:650}}>{sub}</p>}</div>;
const Editor:React.FC<{tex:string,tab?:string,theme?:string,scale?:number,insert?:boolean}>=({tex,tab='Common',theme='Precision',scale=1,insert=false})=>{
 const paper=theme==='Paper',vapor=theme==='Vaporwave',glass=theme==='Glass';const accent=vapor?'#f4a7ea':glass?'#bebcff':paper?'#367859':mint;
 return <div style={{width:850,transform:`scale(${scale})`,transformOrigin:'center',borderRadius:paper?12:23,overflow:'hidden',background:paper?'#f4f0e6':vapor?'linear-gradient(135deg,#25173d,#151a30)':glass?'linear-gradient(130deg,#30354c,#1d2937)':'#1a2023',color:paper?'#303a32':ink,border:'1px solid '+(paper?'#d1cbbb':'#ffffff20'),boxShadow:'0 36px 95px #0006',fontFamily:paper?'Georgia,serif':'Arial,sans-serif'}}>
 <div style={{height:77,display:'flex',alignItems:'center',padding:'0 30px',gap:18,borderBottom:'1px solid #8882'}}><span style={{background:accent+'22',color:accent,borderRadius:10,padding:'8px 13px',fontSize:30}}>⊞</span><div><b style={{fontSize:22}}>MathPaster</b><div style={{fontSize:13,opacity:.5,marginTop:4}}>A space for your equations</div></div><span style={{marginLeft:'auto',fontSize:24,opacity:.6,letterSpacing:22}}>↶ ♧ ⚙</span></div>
 <div style={{padding:'20px 30px',fontSize:16,display:'flex',gap:20,alignItems:'center'}}>Auto-Symbols <span style={{width:38,height:20,borderRadius:20,background:accent,display:'inline-block'}}/><span style={{opacity:.5,marginLeft:10}}>LaTeX Bar ○</span></div>
 <div style={{margin:'0 30px',height:185,background:paper?'#fffcf5':'#0003',borderRadius:12,border:'1px solid #8883',padding:'20px 25px'}}><div style={{fontSize:12,letterSpacing:2,opacity:.55,marginBottom:30}}>YOUR EQUATION</div><div style={{textAlign:'center',color:paper?'#303a32':ink}}><M tex={tex||String.raw`\phantom{x}`} size={52}/></div></div>
 <div style={{display:'flex',gap:8,padding:'25px 30px 18px',fontSize:16}}>{['Common','Calculus','Linear Algebra','Statistics'].map(t=><span key={t} style={{padding:'12px 17px',borderRadius:paper?5:8,color:t===tab?accent:undefined,opacity:t===tab?1:.55,background:t===tab?accent+'18':'transparent'}}>{t}</span>)}</div>
 <div style={{padding:'0 30px 32px',display:'flex',gap:9}}>{(tab==='Linear Algebra'?['[ ]','( )','| |','det','Tr','dim','ker','⊗']:tab==='Calculus'?['∫','∑','∏','lim','∞','∂','d/dx','→']:['α','β','π','θ','√','x²','±','∞']).map(t=><div key={t} style={{background:paper?'#e6e2d7':'#ffffff06',border:'1px solid #8882',borderRadius:paper?5:8,width:89,height:57,display:'flex',alignItems:'center',justifyContent:'center',fontFamily:'Georgia',fontSize:26}}>{t}</div>)}</div>
 <div style={{borderTop:'1px solid #8882',padding:'22px 30px',display:'flex',alignItems:'center',gap:16}}><span style={{fontSize:14,opacity:.5,marginRight:'auto'}}>Ctrl + M · Open anywhere</span><span style={{fontSize:17,opacity:.7}}>Copy LaTeX</span><span style={{padding:'13px 30px',background:accent,borderRadius:9,color:'#10271e',fontWeight:700,fontSize:21,boxShadow:insert?`0 0 35px ${accent}88`:undefined}}>Insert ↵</span></div>
 </div>;
};
const stages=[{start:0,duration:180},{start:180,duration:210},{start:390,duration:270},{start:660,duration:240},{start:900,duration:240},{start:1140,duration:210},{start:1350,duration:240},{start:1590,duration:210}];
const Scene:React.FC<{id:number,duration:number}>=({id,duration})=>{const f=useCurrentFrame();const enter=ramp(f,0,24),exit=1-ramp(f,duration-16,duration);const lift=(1-enter)*45;return <AbsoluteFill style={{opacity:enter*exit,transform:`translateY(${lift}px)`,padding:'100px 120px',justifyContent:'center'}}>
 {id===0&&<><div style={{fontSize:19,color:mint,letterSpacing:5,marginBottom:28}}>YOUR IDEAS ARE MATHEMATICAL.</div><h1 style={{fontSize:106,letterSpacing:-5,lineHeight:1.04,margin:0}}>Why type them<br/>the hard way?</h1><div style={{marginTop:55,padding:'32px 40px',border:'1px solid #ffffff18',borderRadius:20,width:1370,background:'#ffffff04',fontSize:29,lineHeight:1.6,color:'#96a9a0'}}>“A fraction whose numerator is x plus one and whose denominator is the square root of the entire expression x squared plus one…”</div><div style={{position:'absolute',right:155,top:135,opacity:ramp(f,55,85),transform:`scale(${ramp(f,55,105,.88,1)})`,color:mint}}><M tex={String.raw`\frac{x+1}{\sqrt{x^2+1}}`} size={88}/></div></>}
 {id===1&&<div style={{display:'flex',alignItems:'center',gap:90}}><div style={{width:610}}><Caption label="MEET MATHPASTER" title={'Think in math.\nType in math.'} sub="A visual equation editor, right where you’re writing."/><div style={{marginTop:38}}><Key>Ctrl</Key> <span style={{fontSize:26,margin:'0 12px'}}>+</span> <Key>M</Key></div></div><div style={{transform:`translateY(${Math.sin(f/50)*6}px) scale(${ramp(f,15,65,.94,1)})`}}><Editor tex={String.raw`e^{i\pi}+1=0`}/></div></div>}
 {id===2&&<div style={{display:'flex',alignItems:'center',gap:90}}><div style={{width:610}}><Caption label="01 / AUTO-SYMBOLS" title={'Three letters.\nOne integral.'} sub="Type int. Fill the bounds. Keep going."/><div style={{display:'flex',gap:12,marginTop:36}}>{['i','n','t'].map((c,i)=><div key={c} style={{opacity:ramp(f,22+i*12,28+i*12)}}><Key>{c}</Key></div>)}</div><div style={{color:mint,fontSize:22,marginTop:30,opacity:ramp(f,100,125)}}>Auto-Symbols does the formatting.</div></div><Editor tab="Calculus" tex={f<65?'':f<105?String.raw`\int_{\square}^{\square}`:f<145?String.raw`\int_0^1`:f<180?String.raw`\int_0^1 x^2`:String.raw`\int_0^1 x^2\,dx`}/></div>}
 {id===3&&<div style={{display:'flex',alignItems:'center',gap:90}}><div style={{width:610}}><Caption label="02 / NATURAL SHORTCUTS" title={'Complex fractions.\nSimple keystrokes.'}/><div style={{fontSize:26,lineHeight:2,marginTop:30,color:muted}}><Key>/</Key> &nbsp; Create a fraction<br/><Key>sqrt</Key> &nbsp; Insert a square root<br/><Key>↑ ↓</Key> &nbsp; Move between slots</div></div><Editor tex={f<50?String.raw`\frac{\square}{\square}`:f<95?String.raw`\frac{x+1}{\square}`:f<140?String.raw`\frac{x+1}{\sqrt{\square}}`:String.raw`\frac{x+1}{\sqrt{x^2+1}}`}/></div>}
 {id===4&&<div style={{display:'flex',alignItems:'center',gap:90}}><div style={{width:610}}><Caption label="03 / MATRICES" title={'Pick a shape.\nFill the cells.'} sub="Linear Algebra → [ ] → 2 × 2"/><div style={{display:'grid',gridTemplateColumns:'repeat(2,56px)',gap:9,marginTop:35}}>{[0,1,2,3].map(i=><div key={i} style={{height:56,border:'1px solid '+mint,borderRadius:9,background:mint+'22',opacity:ramp(f,20+i*8,36+i*8)}}/>)}</div></div><Editor tab="Linear Algebra" tex={f<65?String.raw`\begin{bmatrix}\square&\square\\\square&\square\end{bmatrix}`:f<100?String.raw`\begin{bmatrix}1&\square\\\square&\square\end{bmatrix}`:f<130?String.raw`\begin{bmatrix}1&2\\\square&\square\end{bmatrix}`:f<160?String.raw`\begin{bmatrix}1&2\\3&\square\end{bmatrix}`:String.raw`\begin{bmatrix}1&2\\3&4\end{bmatrix}`}/></div>}
 {id===5&&<><Caption label="04 / SEND IT" title="From equation to conversation."/><div style={{marginTop:45,display:'flex',gap:55,alignItems:'center'}}><div style={{width:850}}><Editor tex={String.raw`\int_0^1 x^2\,dx`} scale={.8} insert/></div><div style={{width:640,background:'#151d22',border:'1px solid #ffffff22',borderRadius:26,padding:38,transform:`translateX(${(1-ramp(f,35,70))*70}px)`,opacity:ramp(f,30,60)}}><div style={{fontSize:18,color:muted,marginBottom:30}}>YOUR CHAT</div><div style={{fontSize:25,lineHeight:1.7}}>Help me solve this:</div><div style={{fontFamily:'monospace',fontSize:25,color:mint,lineHeight:1.6,marginTop:20,opacity:ramp(f,80,105)}}>{String.raw`$\int_0^1 x^2\,dx$`}</div><div style={{marginTop:30,fontSize:19,color:muted}}>ChatGPT · Claude · Gemini · and more</div></div></div></>}
 {id===6&&<div style={{display:'flex',gap:90,alignItems:'center'}}><div style={{width:610}}><Caption label="05 / MAKE IT YOURS" title={'Your workspace.\nYour personality.'} sub="Precision & Paper are free. Glass & Vaporwave with Pro."/><div style={{marginTop:35,fontSize:31,color:mint}}>{['Precision','Paper','Glass','Vaporwave'][Math.min(3,Math.floor(f/55))]}</div></div><Editor tex={String.raw`\sum_{k=1}^{n}k^2`} theme={['Precision','Paper','Glass','Vaporwave'][Math.min(3,Math.floor(f/55))]}/></div>}
 {id===7&&<div style={{textAlign:'center'}}><div style={{display:'flex',justifyContent:'center',alignItems:'center',gap:22,marginBottom:35}}><Img src={staticFile('showcase-icon.png')} style={{width:76,height:76}}/><span style={{fontSize:38,fontWeight:700,letterSpacing:-1}}>MathPaster</span></div><h1 style={{fontSize:112,lineHeight:1.08,letterSpacing:-5,margin:0}}>Less explaining.<br/><span style={{color:mint}}>More mathematics.</span></h1><div style={{display:'inline-block',marginTop:45,padding:'20px 36px',background:mint,color:'#10271e',borderRadius:14,fontSize:29,fontWeight:650}}>Get the free Chrome extension ↗</div><div style={{fontSize:29,color:muted,marginTop:27}}>mathpaster.com</div></div>}
 </AbsoluteFill>};
export const Showcase2026:React.FC=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:'#0c1418',color:ink,fontFamily:'Arial, sans-serif',overflow:'hidden'}}><AbsoluteFill style={{background:`radial-gradient(ellipse at ${65+Math.sin(f/230)*18}% 40%, #20533e45, transparent 65%)`}}/><AbsoluteFill style={{backgroundImage:'linear-gradient(#ffffff03 1px,transparent 1px),linear-gradient(90deg,#ffffff03 1px,transparent 1px)',backgroundSize:'70px 70px',transform:`translateY(${-f/55%70}px)`,bottom:-70}}/>
 <div style={{position:'absolute',left:65,top:38,color:'#8ba297',fontSize:16,letterSpacing:4}}>MATHPASTER</div><div style={{position:'absolute',right:65,top:38,color:'#637c70',fontSize:16}}>A better way to write math.</div>
 {stages.map((s,i)=><Sequence key={i} from={s.start} durationInFrames={s.duration}><Scene id={i} duration={s.duration}/></Sequence>)}
 <div style={{position:'absolute',bottom:0,left:0,height:3,width:`${f/1799*100}%`,background:mint,opacity:.45}}/>
 <Audio src={staticFile('track.mp3')} volume={f=>ramp(f,0,60,0,.42)*(1-ramp(f,1710,1799))}/>
 {stages.slice(1).map((s,i)=><Sequence key={'w'+i} from={s.start} durationInFrames={40}><Audio src={staticFile('sfx/whoosh.wav')} volume={.13}/></Sequence>)}
 {[412,424,436,710,755,800,970,1000,1030,1060,1220].map((n,i)=><Sequence key={'c'+i} from={n} durationInFrames={15}><Audio src={staticFile('sfx/mouse-click.wav')} volume={.22}/></Sequence>)}
 {[575,820,1060,1245,1615].map((n,i)=><Sequence key={'d'+i} from={n} durationInFrames={50}><Audio src={staticFile('sfx/ding.wav')} volume={.14}/></Sequence>)}
 </AbsoluteFill>};
