// Categorized, render-safe symbol catalog for the "Browse symbols" picker.
//
// Every entry below was validated against the bundled MathLive 0.103.0 by rendering
// it through convertLatexToMarkup and confirming it produces no ML__error markup.
// 453 symbols across 14 categories. Do NOT hand-add unicode-math
// exotica (e.g. \\varhexagon, \\smiley) — MathLive doesn't define them and they render
// as red error boxes. Regenerate via: node scripts/build-symbol-catalog.mjs
//
// `latex` is inserted/rendered as-is (`#0` placeholders handled by renderSymbolFace).
// `name` is the search key (space-separated keywords).
export const SYMBOL_CATALOG = {
  "Greek": [
    { latex: "\\alpha", name: "alpha" },
    { latex: "\\beta", name: "beta" },
    { latex: "\\gamma", name: "gamma" },
    { latex: "\\delta", name: "delta" },
    { latex: "\\epsilon", name: "epsilon" },
    { latex: "\\varepsilon", name: "varepsilon epsilon" },
    { latex: "\\zeta", name: "zeta" },
    { latex: "\\eta", name: "eta" },
    { latex: "\\theta", name: "theta" },
    { latex: "\\vartheta", name: "vartheta theta" },
    { latex: "\\iota", name: "iota" },
    { latex: "\\kappa", name: "kappa" },
    { latex: "\\varkappa", name: "varkappa kappa" },
    { latex: "\\lambda", name: "lambda" },
    { latex: "\\mu", name: "mu" },
    { latex: "\\nu", name: "nu" },
    { latex: "\\xi", name: "xi" },
    { latex: "\\omicron", name: "omicron" },
    { latex: "\\pi", name: "pi" },
    { latex: "\\varpi", name: "varpi pi" },
    { latex: "\\rho", name: "rho" },
    { latex: "\\varrho", name: "varrho rho" },
    { latex: "\\sigma", name: "sigma" },
    { latex: "\\varsigma", name: "varsigma sigma" },
    { latex: "\\tau", name: "tau" },
    { latex: "\\upsilon", name: "upsilon" },
    { latex: "\\phi", name: "phi" },
    { latex: "\\varphi", name: "varphi phi" },
    { latex: "\\chi", name: "chi" },
    { latex: "\\psi", name: "psi" },
    { latex: "\\omega", name: "omega" },
    { latex: "\\digamma", name: "digamma" },
    { latex: "\\Gamma", name: "Gamma" },
    { latex: "\\Delta", name: "Delta" },
    { latex: "\\Theta", name: "Theta" },
    { latex: "\\Lambda", name: "Lambda" },
    { latex: "\\Xi", name: "Xi" },
    { latex: "\\Pi", name: "Pi" },
    { latex: "\\Sigma", name: "Sigma" },
    { latex: "\\Upsilon", name: "Upsilon" },
    { latex: "\\Phi", name: "Phi" },
    { latex: "\\Psi", name: "Psi" },
    { latex: "\\Omega", name: "Omega" },
  ],
  "Operators": [
    { latex: "\\pm", name: "pm" },
    { latex: "\\mp", name: "mp" },
    { latex: "\\times", name: "times" },
    { latex: "\\div", name: "div" },
    { latex: "\\divideontimes", name: "divideontimes" },
    { latex: "\\cdot", name: "cdot" },
    { latex: "\\ast", name: "ast" },
    { latex: "\\star", name: "star" },
    { latex: "\\circ", name: "circ" },
    { latex: "\\bullet", name: "bullet" },
    { latex: "\\bigcirc", name: "bigcirc" },
    { latex: "\\oplus", name: "oplus" },
    { latex: "\\ominus", name: "ominus" },
    { latex: "\\otimes", name: "otimes" },
    { latex: "\\oslash", name: "oslash" },
    { latex: "\\odot", name: "odot" },
    { latex: "\\circledast", name: "circledast" },
    { latex: "\\circledcirc", name: "circledcirc" },
    { latex: "\\circleddash", name: "circleddash" },
    { latex: "\\dagger", name: "dagger" },
    { latex: "\\ddagger", name: "ddagger" },
    { latex: "\\amalg", name: "amalg" },
    { latex: "\\wr", name: "wr" },
    { latex: "\\dotplus", name: "dotplus" },
    { latex: "\\intercal", name: "intercal" },
    { latex: "\\sqcap", name: "sqcap" },
    { latex: "\\sqcup", name: "sqcup" },
    { latex: "\\uplus", name: "uplus" },
    { latex: "\\setminus", name: "setminus" },
    { latex: "\\smallsetminus", name: "smallsetminus" },
    { latex: "\\wedge", name: "wedge" },
    { latex: "\\vee", name: "vee" },
    { latex: "\\land", name: "land" },
    { latex: "\\lor", name: "lor" },
    { latex: "\\barwedge", name: "barwedge" },
    { latex: "\\veebar", name: "veebar" },
    { latex: "\\curlywedge", name: "curlywedge" },
    { latex: "\\curlyvee", name: "curlyvee" },
    { latex: "\\boxtimes", name: "boxtimes" },
    { latex: "\\boxplus", name: "boxplus" },
    { latex: "\\boxminus", name: "boxminus" },
    { latex: "\\boxdot", name: "boxdot" },
    { latex: "\\leftthreetimes", name: "leftthreetimes" },
    { latex: "\\rightthreetimes", name: "rightthreetimes" },
    { latex: "\\ltimes", name: "ltimes" },
    { latex: "\\rtimes", name: "rtimes" },
    { latex: "\\gtrdot", name: "gtrdot" },
    { latex: "\\lessdot", name: "lessdot" },
  ],
  "Big operators": [
    { latex: "\\sum", name: "sum sigma" },
    { latex: "\\prod", name: "prod product" },
    { latex: "\\coprod", name: "coprod" },
    { latex: "\\int", name: "int integral" },
    { latex: "\\iint", name: "iint" },
    { latex: "\\iiint", name: "iiint" },
    { latex: "\\oint", name: "oint" },
    { latex: "\\bigcap", name: "bigcap" },
    { latex: "\\bigcup", name: "bigcup" },
    { latex: "\\bigsqcup", name: "bigsqcup" },
    { latex: "\\bigvee", name: "bigvee" },
    { latex: "\\bigwedge", name: "bigwedge" },
    { latex: "\\bigoplus", name: "bigoplus" },
    { latex: "\\bigotimes", name: "bigotimes" },
    { latex: "\\bigodot", name: "bigodot" },
    { latex: "\\biguplus", name: "biguplus" },
  ],
  "Calculus": [
    { latex: "\\int_{#0}^{#1}", name: "definite integral bounds limits" },
    { latex: "\\int_{#0}^{#1} #2\\, d#3", name: "definite integral dx" },
    { latex: "\\iint_{#0}", name: "double integral region surface" },
    { latex: "\\iiint_{#0}", name: "triple integral region volume" },
    { latex: "\\oint_{#0}", name: "contour integral closed loop line" },
    { latex: "\\sum_{#0}^{#1}", name: "sum sigma bounds series" },
    { latex: "\\sum_{#0=#1}^{#2}", name: "sum index from to bounds" },
    { latex: "\\prod_{#0}^{#1}", name: "product pi bounds" },
    { latex: "\\bigcup_{#0}^{#1}", name: "union bounds" },
    { latex: "\\bigcap_{#0}^{#1}", name: "intersection bounds" },
    { latex: "\\lim_{#0 \\to #1}", name: "limit approaches arrow" },
    { latex: "\\lim_{#0}", name: "limit" },
    { latex: "\\frac{d}{dx}", name: "derivative d dx operator" },
    { latex: "\\frac{d#0}{d#1}", name: "derivative df dx" },
    { latex: "\\frac{d^{2}#0}{d#1^{2}}", name: "second derivative" },
    { latex: "\\frac{\\partial #0}{\\partial #1}", name: "partial derivative" },
    { latex: "\\frac{\\partial^{2}#0}{\\partial #1^{2}}", name: "second partial derivative" },
    { latex: "\\left.#0\\right|_{#1}^{#2}", name: "evaluation bar definite at" },
  ],
  "Fractions & roots": [
    { latex: "\\frac{#0}{#1}", name: "fraction divide over" },
    { latex: "\\dfrac{#0}{#1}", name: "display fraction" },
    { latex: "\\tfrac{#0}{#1}", name: "inline text fraction" },
    { latex: "\\sqrt{#0}", name: "square root radical" },
    { latex: "\\sqrt[#0]{#1}", name: "nth root radical cube" },
    { latex: "\\binom{#0}{#1}", name: "binomial coefficient choose combination" },
    { latex: "#0^{#1}", name: "power superscript exponent" },
    { latex: "#0_{#1}", name: "subscript index" },
    { latex: "#0_{#1}^{#2}", name: "subscript superscript" },
    { latex: "\\overset{#0}{#1}", name: "overset above over" },
    { latex: "\\underset{#0}{#1}", name: "underset below under" },
  ],
  "Functions": [
    { latex: "\\sin", name: "sin" },
    { latex: "\\cos", name: "cos" },
    { latex: "\\tan", name: "tan" },
    { latex: "\\cot", name: "cot" },
    { latex: "\\sec", name: "sec" },
    { latex: "\\csc", name: "csc" },
    { latex: "\\arcsin", name: "arcsin" },
    { latex: "\\arccos", name: "arccos" },
    { latex: "\\arctan", name: "arctan" },
    { latex: "\\sinh", name: "sinh" },
    { latex: "\\cosh", name: "cosh" },
    { latex: "\\tanh", name: "tanh" },
    { latex: "\\log", name: "log" },
    { latex: "\\log_{#0}", name: "log base" },
    { latex: "\\ln", name: "ln natural log" },
    { latex: "\\exp", name: "exp exponential" },
    { latex: "\\deg", name: "deg" },
    { latex: "\\det", name: "det" },
    { latex: "\\dim", name: "dim" },
    { latex: "\\ker", name: "ker" },
    { latex: "\\gcd", name: "gcd" },
    { latex: "\\arg", name: "arg" },
    { latex: "\\max", name: "max" },
    { latex: "\\min", name: "min" },
    { latex: "\\sup", name: "sup" },
    { latex: "\\inf", name: "inf" },
  ],
  "Statistics": [
    { latex: "\\mathbb{E}", name: "expectation expected value E" },
    { latex: "\\mathbb{E}[#0]", name: "expectation expected value of" },
    { latex: "\\operatorname{Var}", name: "variance" },
    { latex: "\\operatorname{Var}(#0)", name: "variance of" },
    { latex: "\\operatorname{Cov}", name: "covariance" },
    { latex: "\\operatorname{Cov}(#0,#1)", name: "covariance of" },
    { latex: "\\operatorname{Corr}", name: "correlation coefficient" },
    { latex: "\\mathbb{P}", name: "probability P" },
    { latex: "\\mathbb{P}(#0)", name: "probability of" },
    { latex: "\\Pr", name: "probability Pr" },
    { latex: "\\mathcal{N}(#0,#1)", name: "normal gaussian distribution" },
    { latex: "\\operatorname{Bin}(#0,#1)", name: "binomial distribution" },
    { latex: "\\operatorname{Pois}(#0)", name: "poisson distribution" },
    { latex: "\\bar{x}", name: "sample mean x bar average" },
    { latex: "\\hat{p}", name: "estimator p hat proportion" },
    { latex: "\\hat{\\mu}", name: "mean estimator mu hat" },
    { latex: "\\hat{\\sigma}", name: "standard deviation estimator sigma hat" },
    { latex: "\\hat{\\theta}", name: "parameter estimator theta hat" },
    { latex: "\\sigma^{2}", name: "variance sigma squared" },
    { latex: "s^{2}", name: "sample variance s squared" },
    { latex: "\\chi^{2}", name: "chi squared" },
    { latex: "#0!", name: "factorial" },
    { latex: "\\operatorname{SE}", name: "standard error" },
    { latex: "\\operatorname{SD}", name: "standard deviation" },
  ],
  "Relations": [
    { latex: "\\leq", name: "leq" },
    { latex: "\\geq", name: "geq" },
    { latex: "\\neq", name: "neq" },
    { latex: "\\equiv", name: "equiv" },
    { latex: "\\approx", name: "approx" },
    { latex: "\\approxeq", name: "approxeq" },
    { latex: "\\cong", name: "cong" },
    { latex: "\\simeq", name: "simeq" },
    { latex: "\\sim", name: "sim" },
    { latex: "\\backsim", name: "backsim" },
    { latex: "\\propto", name: "propto" },
    { latex: "\\asymp", name: "asymp" },
    { latex: "\\doteq", name: "doteq" },
    { latex: "\\ll", name: "ll" },
    { latex: "\\gg", name: "gg" },
    { latex: "\\lll", name: "lll" },
    { latex: "\\ggg", name: "ggg" },
    { latex: "\\leqslant", name: "leqslant" },
    { latex: "\\geqslant", name: "geqslant" },
    { latex: "\\leqq", name: "leqq" },
    { latex: "\\geqq", name: "geqq" },
    { latex: "\\lesssim", name: "lesssim" },
    { latex: "\\gtrsim", name: "gtrsim" },
    { latex: "\\lessgtr", name: "lessgtr" },
    { latex: "\\gtrless", name: "gtrless" },
    { latex: "\\lessapprox", name: "lessapprox" },
    { latex: "\\gtrapprox", name: "gtrapprox" },
    { latex: "\\subset", name: "subset" },
    { latex: "\\supset", name: "supset" },
    { latex: "\\subseteq", name: "subseteq" },
    { latex: "\\supseteq", name: "supseteq" },
    { latex: "\\subsetneq", name: "subsetneq" },
    { latex: "\\supsetneq", name: "supsetneq" },
    { latex: "\\sqsubset", name: "sqsubset" },
    { latex: "\\sqsupset", name: "sqsupset" },
    { latex: "\\sqsubseteq", name: "sqsubseteq" },
    { latex: "\\sqsupseteq", name: "sqsupseteq" },
    { latex: "\\in", name: "in" },
    { latex: "\\ni", name: "ni" },
    { latex: "\\notin", name: "notin" },
    { latex: "\\vdash", name: "vdash" },
    { latex: "\\dashv", name: "dashv" },
    { latex: "\\vDash", name: "vDash" },
    { latex: "\\Vdash", name: "Vdash" },
    { latex: "\\models", name: "models" },
    { latex: "\\perp", name: "perp" },
    { latex: "\\mid", name: "mid" },
    { latex: "\\parallel", name: "parallel" },
    { latex: "\\shortmid", name: "shortmid" },
    { latex: "\\prec", name: "prec" },
    { latex: "\\succ", name: "succ" },
    { latex: "\\preceq", name: "preceq" },
    { latex: "\\succeq", name: "succeq" },
    { latex: "\\precsim", name: "precsim" },
    { latex: "\\succsim", name: "succsim" },
    { latex: "\\precapprox", name: "precapprox" },
    { latex: "\\succapprox", name: "succapprox" },
    { latex: "\\bowtie", name: "bowtie" },
    { latex: "\\smile", name: "smile" },
    { latex: "\\frown", name: "frown" },
    { latex: "\\doteqdot", name: "doteqdot" },
    { latex: "\\risingdotseq", name: "risingdotseq" },
    { latex: "\\fallingdotseq", name: "fallingdotseq" },
    { latex: "\\eqcirc", name: "eqcirc" },
    { latex: "\\circeq", name: "circeq" },
    { latex: "\\triangleq", name: "triangleq" },
    { latex: "\\between", name: "between" },
    { latex: "\\pitchfork", name: "pitchfork" },
  ],
  "Negated": [
    { latex: "\\neq", name: "neq" },
    { latex: "\\notin", name: "notin" },
    { latex: "\\nleq", name: "nleq" },
    { latex: "\\ngeq", name: "ngeq" },
    { latex: "\\nless", name: "nless" },
    { latex: "\\ngtr", name: "ngtr" },
    { latex: "\\nmid", name: "nmid" },
    { latex: "\\nparallel", name: "nparallel" },
    { latex: "\\nsubseteq", name: "nsubseteq" },
    { latex: "\\nsupseteq", name: "nsupseteq" },
    { latex: "\\nsim", name: "nsim" },
    { latex: "\\ncong", name: "ncong" },
    { latex: "\\nprec", name: "nprec" },
    { latex: "\\nsucc", name: "nsucc" },
    { latex: "\\npreceq", name: "npreceq" },
    { latex: "\\nsucceq", name: "nsucceq" },
    { latex: "\\nvdash", name: "nvdash" },
    { latex: "\\nvDash", name: "nvDash" },
    { latex: "\\nVdash", name: "nVdash" },
    { latex: "\\nleftarrow", name: "nleftarrow" },
    { latex: "\\nrightarrow", name: "nrightarrow" },
    { latex: "\\nleftrightarrow", name: "nleftrightarrow" },
    { latex: "\\subsetneqq", name: "subsetneqq" },
    { latex: "\\supsetneqq", name: "supsetneqq" },
    { latex: "\\lneq", name: "lneq" },
    { latex: "\\gneq", name: "gneq" },
  ],
  "Arrows": [
    { latex: "\\leftarrow", name: "leftarrow" },
    { latex: "\\rightarrow", name: "rightarrow" },
    { latex: "\\leftrightarrow", name: "leftrightarrow" },
    { latex: "\\Leftarrow", name: "Leftarrow" },
    { latex: "\\Rightarrow", name: "Rightarrow" },
    { latex: "\\Leftrightarrow", name: "Leftrightarrow" },
    { latex: "\\longleftarrow", name: "longleftarrow" },
    { latex: "\\longrightarrow", name: "longrightarrow" },
    { latex: "\\longleftrightarrow", name: "longleftrightarrow" },
    { latex: "\\Longleftarrow", name: "Longleftarrow" },
    { latex: "\\Longrightarrow", name: "Longrightarrow" },
    { latex: "\\Longleftrightarrow", name: "Longleftrightarrow" },
    { latex: "\\mapsto", name: "mapsto maps to" },
    { latex: "\\longmapsto", name: "longmapsto" },
    { latex: "\\to", name: "to rightarrow" },
    { latex: "\\gets", name: "gets leftarrow" },
    { latex: "\\hookleftarrow", name: "hookleftarrow" },
    { latex: "\\hookrightarrow", name: "hookrightarrow" },
    { latex: "\\leftharpoonup", name: "leftharpoonup" },
    { latex: "\\leftharpoondown", name: "leftharpoondown" },
    { latex: "\\rightharpoonup", name: "rightharpoonup" },
    { latex: "\\rightharpoondown", name: "rightharpoondown" },
    { latex: "\\rightleftharpoons", name: "rightleftharpoons" },
    { latex: "\\leftrightharpoons", name: "leftrightharpoons" },
    { latex: "\\uparrow", name: "uparrow" },
    { latex: "\\downarrow", name: "downarrow" },
    { latex: "\\updownarrow", name: "updownarrow" },
    { latex: "\\Uparrow", name: "Uparrow" },
    { latex: "\\Downarrow", name: "Downarrow" },
    { latex: "\\Updownarrow", name: "Updownarrow" },
    { latex: "\\nearrow", name: "nearrow" },
    { latex: "\\searrow", name: "searrow" },
    { latex: "\\swarrow", name: "swarrow" },
    { latex: "\\nwarrow", name: "nwarrow" },
    { latex: "\\leftleftarrows", name: "leftleftarrows" },
    { latex: "\\rightrightarrows", name: "rightrightarrows" },
    { latex: "\\leftrightarrows", name: "leftrightarrows" },
    { latex: "\\rightleftarrows", name: "rightleftarrows" },
    { latex: "\\upuparrows", name: "upuparrows" },
    { latex: "\\downdownarrows", name: "downdownarrows" },
    { latex: "\\twoheadleftarrow", name: "twoheadleftarrow" },
    { latex: "\\twoheadrightarrow", name: "twoheadrightarrow" },
    { latex: "\\leftarrowtail", name: "leftarrowtail" },
    { latex: "\\rightarrowtail", name: "rightarrowtail" },
    { latex: "\\looparrowleft", name: "looparrowleft" },
    { latex: "\\looparrowright", name: "looparrowright" },
    { latex: "\\curvearrowleft", name: "curvearrowleft" },
    { latex: "\\curvearrowright", name: "curvearrowright" },
    { latex: "\\circlearrowleft", name: "circlearrowleft" },
    { latex: "\\circlearrowright", name: "circlearrowright" },
    { latex: "\\Lsh", name: "Lsh" },
    { latex: "\\Rsh", name: "Rsh" },
    { latex: "\\multimap", name: "multimap" },
    { latex: "\\rightsquigarrow", name: "rightsquigarrow" },
    { latex: "\\leftrightsquigarrow", name: "leftrightsquigarrow" },
    { latex: "\\dashrightarrow", name: "dashrightarrow" },
    { latex: "\\dashleftarrow", name: "dashleftarrow" },
  ],
  "Sets & Logic": [
    { latex: "\\emptyset", name: "emptyset" },
    { latex: "\\varnothing", name: "varnothing" },
    { latex: "\\infty", name: "infty" },
    { latex: "\\aleph", name: "aleph" },
    { latex: "\\beth", name: "beth" },
    { latex: "\\gimel", name: "gimel" },
    { latex: "\\daleth", name: "daleth" },
    { latex: "\\complement", name: "complement" },
    { latex: "\\forall", name: "forall" },
    { latex: "\\exists", name: "exists" },
    { latex: "\\nexists", name: "nexists" },
    { latex: "\\neg", name: "neg" },
    { latex: "\\lnot", name: "lnot" },
    { latex: "\\top", name: "top" },
    { latex: "\\bot", name: "bot" },
    { latex: "\\therefore", name: "therefore" },
    { latex: "\\because", name: "because" },
    { latex: "\\partial", name: "partial" },
    { latex: "\\nabla", name: "nabla" },
    { latex: "\\hbar", name: "hbar" },
    { latex: "\\hslash", name: "hslash" },
    { latex: "\\ell", name: "ell" },
    { latex: "\\wp", name: "wp" },
    { latex: "\\Re", name: "Re" },
    { latex: "\\Im", name: "Im" },
    { latex: "\\imath", name: "imath" },
    { latex: "\\jmath", name: "jmath" },
    { latex: "\\cup", name: "cup" },
    { latex: "\\cap", name: "cap" },
    { latex: "\\mathbb{R}", name: "R reals real numbers blackboard" },
    { latex: "\\mathbb{Z}", name: "Z integers blackboard" },
    { latex: "\\mathbb{N}", name: "N naturals natural numbers blackboard" },
    { latex: "\\mathbb{Q}", name: "Q rationals blackboard" },
    { latex: "\\mathbb{C}", name: "C complex blackboard" },
    { latex: "\\mathbb{H}", name: "H quaternions blackboard" },
    { latex: "\\mathbb{P}", name: "P primes blackboard" },
  ],
  "Delimiters": [
    { latex: "\\langle", name: "langle" },
    { latex: "\\rangle", name: "rangle" },
    { latex: "\\lceil", name: "lceil" },
    { latex: "\\rceil", name: "rceil" },
    { latex: "\\lfloor", name: "lfloor" },
    { latex: "\\rfloor", name: "rfloor" },
    { latex: "\\lbrace", name: "lbrace" },
    { latex: "\\rbrace", name: "rbrace" },
    { latex: "\\lbrack", name: "lbrack" },
    { latex: "\\rbrack", name: "rbrack" },
    { latex: "\\lvert", name: "lvert" },
    { latex: "\\rvert", name: "rvert" },
    { latex: "\\lVert", name: "lVert" },
    { latex: "\\rVert", name: "rVert" },
    { latex: "\\vert", name: "vert" },
    { latex: "\\Vert", name: "Vert" },
    { latex: "\\llbracket", name: "llbracket" },
    { latex: "\\rrbracket", name: "rrbracket" },
    { latex: "\\ulcorner", name: "ulcorner" },
    { latex: "\\urcorner", name: "urcorner" },
    { latex: "\\backslash", name: "backslash" },
  ],
  "Geometry & Misc": [
    { latex: "\\angle", name: "angle" },
    { latex: "\\measuredangle", name: "measuredangle" },
    { latex: "\\sphericalangle", name: "sphericalangle" },
    { latex: "\\triangle", name: "triangle" },
    { latex: "\\triangleleft", name: "triangleleft" },
    { latex: "\\triangleright", name: "triangleright" },
    { latex: "\\bigtriangleup", name: "bigtriangleup" },
    { latex: "\\bigtriangledown", name: "bigtriangledown" },
    { latex: "\\square", name: "square" },
    { latex: "\\blacksquare", name: "blacksquare" },
    { latex: "\\blacktriangle", name: "blacktriangle" },
    { latex: "\\blacktriangledown", name: "blacktriangledown" },
    { latex: "\\blacktriangleleft", name: "blacktriangleleft" },
    { latex: "\\blacktriangleright", name: "blacktriangleright" },
    { latex: "\\bigstar", name: "bigstar" },
    { latex: "\\star", name: "star" },
    { latex: "\\lozenge", name: "lozenge" },
    { latex: "\\blacklozenge", name: "blacklozenge" },
    { latex: "\\diamond", name: "diamond" },
    { latex: "\\Diamond", name: "Diamond" },
    { latex: "\\diamondsuit", name: "diamondsuit" },
    { latex: "\\heartsuit", name: "heartsuit" },
    { latex: "\\clubsuit", name: "clubsuit" },
    { latex: "\\spadesuit", name: "spadesuit" },
    { latex: "\\flat", name: "flat" },
    { latex: "\\natural", name: "natural" },
    { latex: "\\sharp", name: "sharp" },
    { latex: "\\maltese", name: "maltese" },
    { latex: "\\checkmark", name: "checkmark" },
    { latex: "\\dag", name: "dag" },
    { latex: "\\ddag", name: "ddag" },
    { latex: "\\circledR", name: "circledR" },
    { latex: "\\circledS", name: "circledS" },
    { latex: "\\surd", name: "surd" },
    { latex: "\\prime", name: "prime" },
    { latex: "\\backprime", name: "backprime" },
    { latex: "\\cdots", name: "cdots" },
    { latex: "\\ldots", name: "ldots" },
    { latex: "\\vdots", name: "vdots" },
    { latex: "\\ddots", name: "ddots" },
    { latex: "\\colon", name: "colon" },
  ],
  "Decorations": [
    { latex: "\\hat{#0}", name: "hat" },
    { latex: "\\bar{#0}", name: "bar" },
    { latex: "\\vec{#0}", name: "vec vector arrow" },
    { latex: "\\dot{#0}", name: "dot" },
    { latex: "\\ddot{#0}", name: "ddot" },
    { latex: "\\tilde{#0}", name: "tilde" },
    { latex: "\\widehat{#0}", name: "widehat hat" },
    { latex: "\\widetilde{#0}", name: "widetilde tilde" },
    { latex: "\\overline{#0}", name: "overline bar" },
    { latex: "\\underline{#0}", name: "underline" },
    { latex: "\\overrightarrow{#0}", name: "overrightarrow vector" },
    { latex: "\\overleftarrow{#0}", name: "overleftarrow" },
    { latex: "\\boldsymbol{#0}", name: "boldsymbol bold" },
    { latex: "\\mathbf{#0}", name: "mathbf bold" },
    { latex: "\\mathbb{#0}", name: "mathbb blackboard" },
    { latex: "\\mathcal{#0}", name: "mathcal calligraphic" },
    { latex: "\\mathfrak{#0}", name: "mathfrak fraktur" },
    { latex: "\\mathrm{#0}", name: "mathrm roman upright" },
  ],
};
